version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redflagui-app
    restart: always
    ports:
      - "${PORT}:8083"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      API_BASE_URL: "${API_BASE_URL}"
      APP_URL: ${APP_URL}
    entrypoint: /bin/sh
    command: >
      -c "
        mkdir -p /var/www/html/database &&
        touch /var/www/html/database/database.sqlite &&
        chown -R www-data:www-data /var/www/html/database &&
        chmod -R 775 /var/www/html/database &&
        php artisan migrate --force &&
        php artisan config:clear &&
        php-fpm
      "
